-- Angelo Burke

-- 1. Enforce referential integrity by adding foreign key constraints to: ORDERS, REVIEWS, and USERLIBRARY
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);
ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);
ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

-- 2. Display full name and USERNAME of users at least 18 years old
SELECT COUNT(*) AS COUNT_18_PLUS FROM USERBASE
WHERE AGE >= 18;

-- 3. Find max and avg length of USERNAME in USERBASE
SELECT MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH,
ROUND(AVG(LENGTH(USERNAME)), 2) AS AVG_USERNAME_LENGTH
FROM USERBASE;

-- 4. Display every QUESTION that starts with ‘What is’ or ‘What was’
SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%'
OR QUESTION LIKE 'What was%';

-- 5. Display PRODUCTCODE, lowest RATING, and number of reviews, ordered by review count descending
SELECT PRODUCTCODE,
MIN(RATING) AS LOWEST_RATING,
COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;

-- 6. Display PRODUCTCODE ranked at POSITION 1 and number of users who ranked it at that position
SELECT PRODUCTCODE, COUNT(USERID) AS USER_COUNT
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;

-- 7. Display USERID and total amount spent in ORDERS
SELECT USERID, SUM(TOTALAMOUNT) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

-- 8. Display gross profits by PURCHASEDATE, sorted by profit descending
SELECT PURCHASEDATE, SUM(TOTALAMOUNT) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;

-- 9. Display top 5 games by total HOURSPLAYED
SELECT PRODUCTCODE, SUM(HOURSPLAYED) AS TOTAL_HOURS
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TOTAL_HOURS DESC
FETCH FIRST 5 ROWS ONLY;

-- 10. Create a view showing USERID and infraction count, sorted by highest first
CREATE OR REPLACE VIEW UserInfractionCount AS
SELECT USERID, COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;

-- 11. Create a view showing USERID, RULENUM, and number of times broken, sorted by USERID
CREATE OR REPLACE VIEW UserRuleInfraction AS
SELECT USERID, RULENUM, COUNT(*) AS RULE_VIOLATIONS
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;

-- 12. Display RULENUM, PENALTY, and number of times assigned to that RULENUM
SELECT RULENUM, PENALTY, COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;

-- 13. Display avg, max, and min time between DATEUPDATED and DATESUBMITTED for CLOSED tickets
SELECT ROUND(AVG(DATEUPDATED - DATESUBMITTED), 2) AS AVG_DURATION,
MAX(DATEUPDATED - DATESUBMITTED) AS MAX_DURATION,
MIN(DATEUPDATED - DATESUBMITTED) AS MIN_DURATION
FROM USERSUPPORT
WHERE STATUS = 'CLOSED';

-- 14. Display EMAIL, ISSUE, and count of ISSUE for NEW tickets, grouped by DATESUBMITTED and ordered by count
SELECT EMAIL, ISSUE, COUNT(*) AS ISSUE_COUNT
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY DATESUBMITTED, EMAIL, ISSUE
ORDER BY ISSUE_COUNT DESC;

-- 15. Display any user with FIRSTNAME or LASTNAME in their PASSWORD
SELECT USERID, FIRSTNAME, LASTNAME,
PASSWORD
FROM USERBASE
WHERE LOWER(PASSWORD) LIKE '%' || LOWER(FIRSTNAME) || '%'
OR LOWER(PASSWORD) LIKE '%' || LOWER(LASTNAME) || '%';

-- 16. Display PUBLISHER and average PRICE of their products, sorted alphabetically
SELECT PUBLISHER, ROUND(AVG(PRICE), 2) AS AVG_PRICE
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER;

-- 17. Create a view displaying PRODUCTNAME and discounted PRICE (25% off) for products over 5 years old
CREATE OR REPLACE VIEW DiscountedOldProducts AS
SELECT PRODUCTNAME, ROUND(PRICE * 0.75, 2) AS DISCOUNTED_PRICE
FROM PRODUCTLIST
WHERE RELEASEDATE <= ADD_MONTHS(SYSDATE, -60);

-- 18. Calculate max and min PRICE by GENRE
SELECT GENRE,
MAX(PRICE) AS MAX_PRICE, MIN(PRICE) AS MIN_PRICE
FROM PRODUCTLIST
GROUP BY GENRE;

-- 19. Create a view displaying all CHATLOG messages from the past week
CREATE OR REPLACE VIEW RecentChatMessages AS
SELECT * FROM CHATLOG

-- 20. Create a view displaying USERID, DATEASSIGNED, and PENALTY for infractions within the last month
CREATE OR REPLACE VIEW RecentInfractions AS
SELECT USERID, DATEASSIGNED, PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL


