-- Angelo Burke

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, STATUS, DATEUPDATED)
VALUES (501, 'toby@gmail.com', 'Issue with Toby246', 'NEW', SYSDATE);
UPDATE USERBASE SET EMAIL = 'toby@gmail.com', PASSWORD = 'TobyPass123' WHERE USERID = 1;
INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, STATUS, DATEUPDATED)
VALUES (501, 'toby@gmail.com', 'Issue with Toby246', 'NEW', SYSDATE);
INSERT INTO USERBASE (USERID, USERNAME, BIRTHDAY)
VALUES (1, 'Toby246', DATE '1995-01-10');
INSERT INTO USERBASE (USERID, USERNAME, BIRTHDAY)
VALUES (2, 'XxFazeFanxX', DATE '2000-02-15');
INSERT INTO USERBASE (USERID, USERNAME, BIRTHDAY)
VALUES (3, 'chillguy', DATE '1998-07-20');
INSERT INTO FRIENDLIST (USERID, FRIENDID)
INSERT INTO FRIENDLIST (USERID, FRIENDID) VALUES (1, 2);
INSERT INTO FRIENDLIST (USERID, FRIENDID) VALUES (1, 3);
INSERT INTO FRIENDLIST (USERID, FRIENDID) VALUES (2, 1);
INSERT INTO FRIENDLIST (USERID, FRIENDID) VALUES (3, 1);
INSERT INTO PRODUCTLIST (PRODUCTCODE, PRODUCTNAME, RELEASEDATE, PRICE, DESCRIPTION)
VALUES (101, 'Elder Quest', DATE '2020-05-20', 59.99, 'Epic RPG');
INSERT INTO PRODUCTLIST (PRODUCTCODE, PRODUCTNAME, RELEASEDATE, PRICE, DESCRIPTION)
VALUES (102, 'Racing Blast', DATE '2021-08-15', 39.99, 'High-speed racing game');
INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (1, 101, 1);
INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (2, 102, 2);

-- 1. Display every USERNAME and the lowest RATING they have left in a review
SELECT USERBASE.USERNAME, MIN(REVIEWS.RATING) AS LOWEST_RATING
FROM USERBASE
LEFT JOIN REVIEWS ON USERBASE.USERID = REVIEWS.USERID
GROUP BY USERBASE.USERNAME;

-- 2. Display every user's EMAIL, QUESTION, and ANSWER
SELECT USERBASE.EMAIL, SECURITYQUESTION.QUESTION, SECURITYQUESTION.ANSWER
FROM USERBASE
LEFT JOIN SECURITYQUESTION ON USERBASE.USERID = SECURITYQUESTION.USERID;

-- 3. Display the FIRSTNAME, EMAIL, and WALLETFUNDS of every user that does not have a WISHLIST
SELECT USERBASE.FIRSTNAME, USERBASE.EMAIL, USERBASE.WALLETFUNDS
FROM USERBASE
LEFT JOIN WISHLIST ON USERBASE.USERID = WISHLIST.USERID
WHERE WISHLIST.USERID IS NULL;

-- 4. Display every USERNAME and number of products they have ordered
SELECT USERBASE.USERNAME, COUNT(ORDERS.ORDERID) AS PRODUCT_ORDERED
FROM USERBASE
JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
GROUP BY USERBASE.USERNAME;

-- 5. Display the age of any user who has ordered a product within the last 6 months
SELECT (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM USERBASE.BIRTHDAY)) AS AGE
FROM USERBASE
JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
WHERE ORDERS.PURCHASEDATE >= ADD_MONTHS(SYSDATE, -6);

-- 6. Display the USERNAME and BIRTHDAY of the user who has the highest friend count
SELECT USERBASE.USERNAME, USERBASE.BIRTHDAY
FROM USERBASE
WHERE USERBASE.USERID = (
SELECT USERID
FROM FRIENDSLIST
GROUP BY USERID
ORDER BY COUNT(FRIENDID) DESC
FETCH FIRST 1 ROW ONLY
);

-- 7. Display the PRODUCTNAME, RELEASEDATE, PRICE, and DESCRIPTION for any product found in the WISHLIST table
SELECT PRODUCTLIST.PRODUCTNAME, PRODUCTLIST.RELEASEDATE, PRODUCTLIST.PRICE, PRODUCTLIST.DESCRIPTION
FROM PRODUCTLIST
WHERE PRODUCTLIST.PRODUCTCODE IN (
SELECT DISTINCT PRODUCTCODE
FROM WISHLIST
);

-- 8. Display the PRODUCTNAME, highest RATING, and number of reviews for each product in the REVIEWS table. Order the results in descending order of the RATING
SELECT PRODUCTLIST.PRODUCTNAME, MAX(REVIEWS.RATING) AS HIGHEST_RATING, COUNT(REVIEWS.REVIEWID) AS REVIEW_COUNT
FROM PRODUCTLIST
JOIN REVIEWS ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE
GROUP BY PRODUCTLIST.PRODUCTNAME
ORDER BY HIGHEST_RATING DESC;

-- 9. Create a view that displays the PRODUCTNAME, GENRE, and RATING for every product with a 5 or a 1 RATING. Order the results in ascending order of the RATING
CREATE OR REPLACE VIEW HighLowRatedProducts AS
SELECT PRODUCTLIST.PRODUCTNAME, PRODUCTLIST.GENRE, REVIEWS.RATING
FROM PRODUCTLIST
JOIN REVIEWS ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE
WHERE REVIEWS.RATING IN (1, 5)
ORDER BY REVIEWS.RATING ASC;

-- 10. Display the count of products ordered, grouped by GENRE. Order the results in alphabetical order of GENRE
SELECT PRODUCTLIST.GENRE, COUNT(ORDERS.ORDERID) AS PRODUCT_COUNT
FROM PRODUCTLIST
JOIN ORDERS ON PRODUCTLIST.PRODUCTCODE = ORDERS.PRODUCTCODE
GROUP BY PRODUCTLIST.GENRE
ORDER BY PRODUCTLIST.GENRE;

-- 11. Create a view that displays each PUBLISHER, the average PRICE, and the sum of HOURSPLAYED for their products
CREATE OR REPLACE VIEW PublisherProductStats AS
SELECT PRODUCTLIST.PUBLISHER,ROUND(AVG(PRODUCTLIST.PRICE), 2) AS AVG_PRICE, SUM(USERLIBRARY.HOURSPLAYED) AS TOTAL_HOURS_PLAYED
FROM PRODUCTLIST
LEFT JOIN USERLIBRARY ON PRODUCTLIST.PRODUCTCODE = USERLIBRARY.PRODUCTCODE
GROUP BY PRODUCTLIST.PUBLISHER;

-- 12. Display the sum of money spent on products and their corresponding PUBLISHER, from the ORDERS table. Order the results in descending order of the sum of money spent
SELECT PRODUCTLIST.PUBLISHER, SUM(ORDERS.TOTALAMOUNT) AS TOTAL_MONEY_SPENT
FROM ORDERS
JOIN PRODUCTLIST ON ORDERS.PRODUCTCODE = PRODUCTLIST.PRODUCTCODE
GROUP BY PRODUCTLIST.PUBLISHER
ORDER BY TOTAL_MONEY_SPENT DESC;

-- 13. Display TICKETID, USERNAME, EMAIL, and ISSUE for tickets with STATUS ‘NEW’ or ‘IN PROGRESS’, sorted by latest DATEUPDATED
SELECT TICKETID, USERBASE.USERNAME, USERBASE.EMAIL, ISSUE
FROM USERSUPPORT
JOIN USERBASE ON USERSUPPORT.USERID = USERBASE.USERID
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED DESC;

-- 14. Display the USERNAME and count of TICKETID that users have submitted for support
SELECT USERBASE.USERNAME, COUNT(USERSUPPORT.TICKETID) AS TICKET_COUNT
FROM USERSUPPORT
JOIN USERBASE ON USERSUPPORT.USERID = USERBASE.USERID
GROUP BY USERBASE.USERNAME;

-- 15. Display USERID and EMAIL of any user who has submitted a support ticket using their FIRSTNAME, LASTNAME, or combination of both in their EMAIL
SELECT DISTINCT USERBASE.USERID, USERBASE.EMAIL
FROM USERSUPPORT
JOIN USERBASE ON USERSUPPORT.USERID = USERBASE.USERID
WHERE LOWER(USERBASE.EMAIL) LIKE '%' || LOWER(USERBASE.FIRSTNAME) || '%'
OR LOWER(USERBASE.EMAIL) LIKE '%' || LOWER(USERBASE.LASTNAME) || '%'
OR LOWER(USERBASE.EMAIL) LIKE '%' || LOWER(USERBASE.FIRSTNAME || USERBASE.LASTNAME) || '%';

-- 16. Display EMAIL of users with ‘NEW’ or ‘IN PROGRESS’ support tickets, where EMAIL is not in USERBASE
SELECT DISTINCT USERSUPPORT.EMAIL
FROM USERSUPPORT
LEFT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE USERSUPPORT.STATUS IN ('NEW', 'IN PROGRESS')
AND USERBASE.EMAIL IS NULL;

-- 17. Display TICKETID, FIRSTNAME, LASTNAME, and USERNAME of users whose USERNAME is mentioned in the ISSUE
SELECT USERSUPPORT.TICKETID, USERBASE.FIRSTNAME, USERBASE.LASTNAME, USERBASE.USERNAME
FROM USERSUPPORT
JOIN USERBASE ON USERSUPPORT.USERID = USERBASE.USERID
WHERE LOWER(ISSUE) LIKE '%' || LOWER(USERBASE.USERNAME) || '%';

-- 18. Display USERNAME and PASSWORD associated with EMAIL from the support tickets
SELECT DISTINCT USERBASE.USERNAME, USERBASE.PASSWORD
FROM USERSUPPORT
JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL;

-- 19. Create view: USERNAME, DATEASSIGNED, and PENALTY for users with PENALTY not null within last month
SELECT USERBASE.USERNAME, INFRACTIONS.DATEASSIGNED, INFRACTIONS.PENALTY
FROM INFRACTIONS
JOIN USERBASE ON INFRACTIONS.USERID = USERBASE.USERID
WHERE INFRACTIONS.PENALTY IS NOT NULL
AND INFRACTIONS.DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);

-- 20. Display USERNAME and EMAIL of users at least 18 years old with no infractions in the last 4 months
SELECT USERBASE.USERNAME, USERBASE.EMAIL
FROM USERBASE
WHERE AGE >= 18
AND USERID NOT IN (
SELECT DISTINCT USERID
FROM INFRACTIONS
WHERE DATEASSIGNED >= ADD_MONTHS(SYSDATE, -4)
);

-- 21. Display USERNAME, DATEASSIGNED, and full guideline name (RULENUM and TITLE separated by a space)
SELECT USERBASE.USERNAME, INFRACTIONS.DATEASSIGNED, INFRACTIONS.RULENUM || ' ' || COMMUNITYRULES.TITLE AS FULL_GUIDELINE_NAME
FROM INFRACTIONS
JOIN USERBASE ON INFRACTIONS.USERID = USERBASE.USERID
JOIN COMMUNITYRULES ON INFRACTIONS.RULENUM = COMMUNITYRULES.RULENUM;

-- 22. Display USERID, USERNAME, EMAIL, and sum of SEVERITYPOINTS
SELECT USERBASE.USERID, USERBASE.USERNAME, USERBASE.EMAIL, SUM(INFRACTIONS.SEVERITYPOINTS) AS TOTAL_SEVERITY
FROM USERBASE
JOIN INFRACTIONS ON USERBASE.USERID = INFRACTIONS.USERID
GROUP BY USERBASE.USERID, USERBASE.USERNAME, USERBASE.EMAIL;

-- 23. Display TITLE, DESCRIPTION, and PENALTY for all infractions assigned
SELECT COMMUNITYRULES.TITLE, COMMUNITYRULES.DESCRIPTION, INFRACTIONS.PENALTY
FROM INFRACTIONS
JOIN COMMUNITYRULES ON INFRACTIONS.RULENUM = COMMUNITYRULES.RULENUM;

-- 24. Display USERNAME and count of infractions for users with at least 15 infractions
SELECT USERBASE.USERNAME, COUNT(INFRACTIONS.RULENUM) AS INFRACTION_COUNT
FROM INFRACTIONS
JOIN USERBASE ON INFRACTIONS.USERID = USERBASE.USERID
GROUP BY USERBASE.USERNAME
HAVING COUNT(INFRACTIONS.RULENUM) >= 15;
