-- 1.1 Alter PRODUCTLIST table to include PRICE and DESCRIPTION columns
ALTER TABLE PRODUCTLIST
ADD (PRICE NUMBER(6,2), DESCRIPTION VARCHAR2(255));

-- 1.2 Update PRODUCTLIST with data from STOREFRONT
-- (Assumes PRODUCTLIST and STOREFRONT share a common PRODUCTID column)

UPDATE PRODUCTLIST PL
SET (PRICE, DESCRIPTION) = (
  SELECT SF.PRICE, SF.DESCRIPTION
  FROM STOREFRONT SF
  WHERE SF.PRODUCTID = PL.PRODUCTID
)
WHERE EXISTS (
  SELECT 1 FROM STOREFRONT SF WHERE SF.PRODUCTID = PL.PRODUCTID
);

-- 1.3 Drop the STOREFRONT table
DROP TABLE STOREFRONT;

-- 2.1 Create CHATLOG table
CREATE TABLE CHATLOG (
  CHATID NUMBER(3),
  RECEIVERID NUMBER(3),
  SENDERID NUMBER(3),
  DATESENT DATE,
  CONTENT VARCHAR2(250),
  CONSTRAINT PK_CHATLOG PRIMARY KEY (CHATID),
  CONSTRAINT FK_RECEIVER FOREIGN KEY (RECEIVERID) REFERENCES USERBASE(USERID),
  CONSTRAINT FK_SENDER FOREIGN KEY (SENDERID) REFERENCES USERBASE(USERID)
);

-- 2.2 Insert 10–15 sample rows into CHATLOG
INSERT INTO CHATLOG VALUES (1, 101, 102, TO_DATE('2025-02-01', 'YYYY-MM-DD'), 'Hey bro, wassup');
INSERT INTO CHATLOG VALUES (2, 102, 101, TO_DATE('2025-02-01', 'YYYY-MM-DD'), 'Nthn much, you?');
INSERT INTO CHATLOG VALUES (3, 103, 104, TO_DATE('2025-02-01', 'YYYY-MM-DD'), 'You ready to hop on COD?');
INSERT INTO CHATLOG VALUES (4, 104, 103, TO_DATE('2025-02-01', 'YYYY-MM-DD'), 'Yeah, join the party already');
INSERT INTO CHATLOG VALUES (5, 105, 101, TO_DATE('2025-03-07', 'YYYY-MM-DD'), 'Aye bro, you tryna run duos?');
INSERT INTO CHATLOG VALUES (6, 106, 105, TO_DATE('2025-03-07', 'YYYY-MM-DD'), 'Yea man, lets get it');
INSERT INTO CHATLOG VALUES (7, 107, 106, TO_DATE('2025-04-09', 'YYYY-MM-DD'), 'Hey bro, I’m bouta hop off, I got work tommarow');
INSERT INTO CHATLOG VALUES (8, 108, 107, TO_DATE('2025-04-09', 'YYYY-MM-DD'), 'That’s cool bro, we can play again another day');
INSERT INTO CHATLOG VALUES (9, 109, 108, TO_DATE('2025-05-05', 'YYYY-MM-DD'), 'I sent you an invite to the party, did you get it?');
INSERT INTO CHATLOG VALUES (10, 110, 109, TO_DATE('2025-05-05', 'YYYY-MM-DD'), 'Yeah I got it');
INSERT INTO CHATLOG VALUES (11, 101, 110, TO_DATE('2025-06-02', 'YYYY-MM-DD'), 'Was there an update?');
INSERT INTO CHATLOG VALUES (12, 102, 103, TO_DATE('2025-06-02', 'YYYY-MM-DD'), 'Yeah, you should check the patch notes, they’ve fixed a lot of bugs');
INSERT INTO CHATLOG VALUES (13, 103, 102, TO_DATE('2025-06-02', 'YYYY-MM-DD'), 'Dude that’s great, I’ll check them out right away');

-- 3.1 Create FRIENDSLIST table
CREATE TABLE FRIENDSLIST (
  USERID NUMBER(3),
  FRIENDID NUMBER(3),
  CONSTRAINT PK_FRIENDSLIST PRIMARY KEY (USERID, FRIENDID),
  CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
  CONSTRAINT FK_FRIENDID FOREIGN KEY (FRIENDID) REFERENCES USERBASE(USERID)
);

-- 3.2 Insert 10–15 sample rows into FRIENDSLIST
INSERT INTO FRIENDSLIST VALUES (101, 102);
INSERT INTO FRIENDSLIST VALUES (102, 101);
INSERT INTO FRIENDSLIST VALUES (103, 104);
INSERT INTO FRIENDSLIST VALUES (104, 103);
INSERT INTO FRIENDSLIST VALUES (105, 106);
INSERT INTO FRIENDSLIST VALUES (106, 105);
INSERT INTO FRIENDSLIST VALUES (107, 108);
INSERT INTO FRIENDSLIST VALUES (108, 107);
INSERT INTO FRIENDSLIST VALUES (109, 110);
INSERT INTO FRIENDSLIST VALUES (110, 109);
INSERT INTO FRIENDSLIST VALUES (101, 103);
INSERT INTO FRIENDSLIST VALUES (103, 101);
INSERT INTO FRIENDSLIST VALUES (104, 105);

-- 4.1 Create WISHLIST table
CREATE TABLE WISHLIST (
  USERID NUMBER(3),
  PRODUCTCODE VARCHAR2(5),
  POSITION NUMBER(3),
  CONSTRAINT PK_WISHLIST PRIMARY KEY (USERID, PRODUCTCODE),
  CONSTRAINT FK_WISHLIST_USER FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
  CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE)
);

-- 4.2 Insert 10–15 sample rows into WISHLIST
INSERT INTO WISHLIST VALUES (101, 'P001', 1);
INSERT INTO WISHLIST VALUES (101, 'P003', 2);
INSERT INTO WISHLIST VALUES (102, 'P004', 1);
INSERT INTO WISHLIST VALUES (103, 'P002', 1);
INSERT INTO WISHLIST VALUES (103, 'P005', 2);
INSERT INTO WISHLIST VALUES (104, 'P003', 1);
INSERT INTO WISHLIST VALUES (104, 'P006', 2);
INSERT INTO WISHLIST VALUES (105, 'P007', 1);
INSERT INTO WISHLIST VALUES (106, 'P001', 1);
INSERT INTO WISHLIST VALUES (107, 'P004', 1);
INSERT INTO WISHLIST VALUES (107, 'P002', 2);
INSERT INTO WISHLIST VALUES (108, 'P005', 1);
INSERT INTO WISHLIST VALUES (109, 'P003', 1);
INSERT INTO WISHLIST VALUES (110, 'P007', 1);

-- 5.1 Create USERPROFILE table
CREATE TABLE USERPROFILE (
  USERID NUMBER(3),
  IMAGEFILE VARCHAR2(250),
  DESCRIPTION VARCHAR2(250),
  CONSTRAINT PK_USERPROFILE PRIMARY KEY (USERID),
  CONSTRAINT FK_USERPROFILE_USER FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
);

-- 5.2 Insert 10–15 sample rows into USERPROFILE
INSERT INTO USERPROFILE VALUES (101, '/images/users/101.jpg', 'Gamer and tech enthusiast.');
INSERT INTO USERPROFILE VALUES (102, '/images/users/102.jpg', 'Loves strategy games!');
INSERT INTO USERPROFILE VALUES (103, '/images/users/103.jpg', 'Retro games style enjoyer.');
INSERT INTO USERPROFILE VALUES (104, '/images/users/104.jpg', 'New to the platform.');
INSERT INTO USERPROFILE VALUES (105, '/images/users/105.jpg', 'I play whenever I’m free.');
INSERT INTO USERPROFILE VALUES (106, '/images/users/106.jpg', 'FPS are where I’m best at.');
INSERT INTO USERPROFILE VALUES (107, '/images/users/107.jpg', 'Open world games are my favorite.');
INSERT INTO USERPROFILE VALUES (108, '/images/users/108.jpg', 'Looking for co-op players.');
INSERT INTO USERPROFILE VALUES (109, '/images/users/109.jpg', 'I stream on weekends.');
INSERT INTO USERPROFILE VALUES (110, '/images/users/110.jpg', 'Always ready for a 1v1!');
INSERT INTO USERPROFILE VALUES (111, '/images/users/111.jpg', 'Support main in just about every game.');
INSERT INTO USERPROFILE VALUES (112, '/images/users/112.jpg', 'reccomend me some games, I’m bored.');

-- 6.1 Create SECURITYQUESTION table
CREATE TABLE SECURITYQUESTION (
  QUESTIONID NUMBER,
  USERID NUMBER(3),
  QUESTION VARCHAR2(250),
  ANSWER VARCHAR2(250),
  CONSTRAINT PK_SECURITYQUESTION PRIMARY KEY (QUESTIONID),
  CONSTRAINT FK_SECURITYQUESTION_USER FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
);

-- 6.2 Insert 10–15 sample rows into SECURITYQUESTION
INSERT INTO SECURITYQUESTION VALUES (1, 101, 'What was the name of your first pet?', 'Buster');
INSERT INTO SECURITYQUESTION VALUES (2, 102, 'What is your mother’s maiden name?', 'Smith');
INSERT INTO SECURITYQUESTION VALUES (3, 103, 'What city were you born in?', 'Denver');
INSERT INTO SECURITYQUESTION VALUES (4, 104, 'What is your favorite color?', 'Green');
INSERT INTO SECURITYQUESTION VALUES (5, 105, 'What is your favorite game?', 'Fallout');
INSERT INTO SECURITYQUESTION VALUES (6, 106, 'What was your childhood nickname?', 'Spades');
INSERT INTO SECURITYQUESTION VALUES (7, 107, 'What was your first car?', 'Honda Civic');
INSERT INTO SECURITYQUESTION VALUES (8, 108, 'What elementary school did you attend?', 'Lincoln');
INSERT INTO SECURITYQUESTION VALUES (9, 109, 'What is your favorite food?', 'Pizza');
INSERT INTO SECURITYQUESTION VALUES (10, 110, 'What is your dream job?', 'Game Developer');
INSERT INTO SECURITYQUESTION VALUES (11, 111, 'Who was your childhood hero?', 'Batman');
INSERT INTO SECURITYQUESTION VALUES (12, 112, 'Where did you go on your first trip?', 'Hawaii');
INSERT INTO SECURITYQUESTION VALUES (13, 101, 'What was your high school mascot?', 'Falcon');

-- 7.1 Create COMMUNITYRULES table
CREATE TABLE COMMUNITYRULES (
  RULENUM NUMBER(3),
  TITLE VARCHAR2(250),
  DESCRIPTION VARCHAR2(250),
  SEVERITYPOINT NUMBER(4),
  CONSTRAINT PK_COMMUNITYRULES PRIMARY KEY (RULENUM)
);

-- 7.2 Insert 10–15 sample rows into COMMUNITYRULES
INSERT INTO COMMUNITYRULES VALUES (1, 'No Harassment', 'Users must not harass or bully others.', 100);
INSERT INTO COMMUNITYRULES VALUES (2, 'Respect Privacy', 'Do not share personal information of others.', 90);
INSERT INTO COMMUNITYRULES VALUES (3, 'No Hate Speech', 'Any form of hate speech is prohibited.', 95);
INSERT INTO COMMUNITYRULES VALUES (4, 'No Cheating', 'Using cheats or exploits is forbidden.', 85);
INSERT INTO COMMUNITYRULES VALUES (5, 'No self-promotion', 'Advertising your own server, channel, website, etc, is not allowed unless given permission.', 70);
INSERT INTO COMMUNITYRULES VALUES (6, 'Spam Prohibited', 'Do not spam in chat or forums.', 60);
INSERT INTO COMMUNITYRULES VALUES (7, 'No NSFW', 'No type of inappropiate content is allowed.', 80);
INSERT INTO COMMUNITYRULES VALUES (8, 'Impersonation', 'Do not impersonate staff or other users.', 75);
INSERT INTO COMMUNITYRULES VALUES (9, 'Appropriate Names', 'Usernames must be appropriate and non-offensive.', 65);
INSERT INTO COMMUNITYRULES VALUES (10, 'Respect Moderators', 'Comply with moderator instructions and rulels.', 90);
INSERT INTO COMMUNITYRULES VALUES (11, 'No Threats', 'Users should not make threats of any kind to another user.', 50);

-- 8.1 Create INFRACTIONS table
CREATE TABLE INFRACTIONS (
  INFRACTIONID NUMBER,
  USERID NUMBER(3),
  RULENUM NUMBER(3),
  DATEASSIGNED DATE,
  PENALTY VARCHAR2(250),
  CONSTRAINT PK_INFRACTIONS PRIMARY KEY (INFRACTIONID),
  CONSTRAINT FK_INFRACTIONS_USER FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
  CONSTRAINT FK_INFRACTIONS_RULE FOREIGN KEY (RULENUM) REFERENCES COMMUNITYRULES(RULENUM)
);

-- 8.2 Insert 10–15 sample rows into INFRACTIONS
INSERT INTO INFRACTIONS VALUES (1, 101, 1, TO_DATE('2025-04-01', 'YYYY-MM-DD'), '3-day suspension');
INSERT INTO INFRACTIONS VALUES (2, 102, 3, TO_DATE('2025-04-03', 'YYYY-MM-DD'), '7-day suspension');
INSERT INTO INFRACTIONS VALUES (3, 103, 4, TO_DATE('2025-04-05', 'YYYY-MM-DD'), '14-day suspension');
INSERT INTO INFRACTIONS VALUES (4, 104, 5, TO_DATE('2025-04-07', 'YYYY-MM-DD'), '30-day suspension');
INSERT INTO INFRACTIONS VALUES (5, 105, 2, TO_DATE('2025-04-10', 'YYYY-MM-DD'), 'Account locked');
INSERT INTO INFRACTIONS VALUES (6, 106, 6, TO_DATE('2025-04-12', 'YYYY-MM-DD'), '1st Warning');
INSERT INTO INFRACTIONS VALUES (7, 107, 8, TO_DATE('2025-04-13', 'YYYY-MM-DD'), '2nd Warning');
INSERT INTO INFRACTIONS VALUES (8, 108, 10, TO_DATE('2025-04-14', 'YYYY-MM-DD'), 'Account banned perm');
INSERT INTO INFRACTIONS VALUES (9, 109, 7, TO_DATE('2025-04-15', 'YYYY-MM-DD'), 'Content removed');
INSERT INTO INFRACTIONS VALUES (10, 110, 1, TO_DATE('2025-04-17', 'YYYY-MM-DD'), 'Chat mute for 3 days');
INSERT INTO INFRACTIONS VALUES (11, 111, 9, TO_DATE('2025-04-18', 'YYYY-MM-DD'), 'Username changed by admin');

-- 9.1 Create USERSUPPORT table
CREATE TABLE USERSUPPORT (
  TICKETID NUMBER,
  EMAIL VARCHAR2(250),
  ISSUE VARCHAR2(250),
  DATESUBMITTED DATE,
  DATEUPDATED DATE,
  STATUS VARCHAR2(250),
  CONSTRAINT PK_USERSUPPORT PRIMARY KEY (TICKETID)
);

-- 9.2 Insert 10–15 sample rows into USERSUPPORT
INSERT INTO USERSUPPORT VALUES (1, 'angeloburke@gmail.com', 'Cannot login to account', TO_DATE('2025-04-01','YYYY-MM-DD'), TO_DATE('2025-04-01','YYYY-MM-DD'), 'NEW');
INSERT INTO USERSUPPORT VALUES (2, 'jane@gmail.com', 'Forgot password', TO_DATE('2025-04-03','YYYY-MM-DD'), TO_DATE('2025-04-04','YYYY-MM-DD'), 'IN PROGRESS');
INSERT INTO USERSUPPORT VALUES (3, 'mike@gmail.com', 'Report bug in game', TO_DATE('2025-04-05','YYYY-MM-DD'), TO_DATE('2025-04-06','YYYY-MM-DD'), 'CLOSED');
INSERT INTO USERSUPPORT VALUES (4, 'lisa@gmail.com', 'Billing issue with purchase', TO_DATE('2025-04-06','YYYY-MM-DD'), TO_DATE('2025-04-06','YYYY-MM-DD'), 'NEW');
INSERT INTO USERSUPPORT VALUES (5, 'tom@gmail.com', 'Request refund', TO_DATE('2025-04-07','YYYY-MM-DD'), TO_DATE('2025-04-10','YYYY-MM-DD'), 'IN PROGRESS');
INSERT INTO USERSUPPORT VALUES (6, 'nina@gmail.com', 'Game crashes at startup', TO_DATE('2025-04-08','YYYY-MM-DD'), TO_DATE('2025-04-08','YYYY-MM-DD'), 'CLOSED');
INSERT INTO USERSUPPORT VALUES (7, 'kyle@gmail.com', 'Cannot change username', TO_DATE('2025-04-09','YYYY-MM-DD'), TO_DATE('2025-04-09','YYYY-MM-DD'), 'NEW');
INSERT INTO USERSUPPORT VALUES (8, 'ella@gmail.com', 'Double charged for subscription', TO_DATE('2025-04-10','YYYY-MM-DD'), TO_DATE('2025-04-12','YYYY-MM-DD'), 'IN PROGRESS');
INSERT INTO USERSUPPORT VALUES (9, 'ryan@gmail.com', 'Ban appeal', TO_DATE('2025-04-11','YYYY-MM-DD'), TO_DATE('2025-04-13','YYYY-MM-DD'), 'CLOSED');
INSERT INTO USERSUPPORT VALUES (10, 'sara@gmail.com', 'Two-factor authentication not working', TO_DATE('2025-04-12','YYYY-MM-DD'), TO_DATE('2025-04-12','YYYY-MM-DD'), 'NEW');
INSERT INTO USERSUPPORT VALUES (11, 'leo@gmail.com', 'Chat feature disabled', TO_DATE('2025-04-13','YYYY-MM-DD'), TO_DATE('2025-04-14','YYYY-MM-DD'), 'IN PROGRESS');
INSERT INTO USERSUPPORT VALUES (12, 'tina@gmail.com', 'Need help updating payment method', TO_DATE('2025-04-15','YYYY-MM-DD'), TO_DATE('2025-04-16','YYYY-MM-DD'), 'CLOSED');
INSERT INTO USERSUPPORT VALUES (13, 'mark@gmail.com', 'Account hacked', TO_DATE('2025-04-15','YYYY-MM-DD'), TO_DATE('2025-04-15','YYYY-MM-DD'), 'NEW');

CREATE VIEW UNIQUE_SECURITY_QUESTIONS AS
SELECT DISTINCT QUESTION
FROM SECURITYQUESTION;

CREATE VIEW ACTIVE_TICKETS_VIEW AS
SELECT TICKETID, EMAIL, ISSUE, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED ASC;
